import avatar1 from "/images/avatar/avatar-1.jpg";
import avatar2 from "/images/avatar/avatar-2.jpg";
import avatar3 from "/images/avatar/avatar-3.jpg";
import avatar4 from "/images/avatar/avatar-4.jpg";
import avatar5 from "/images/avatar/avatar-5.jpg";
import avatar6 from "/images/avatar/avatar-6.jpg";
import avatar7 from "/images/avatar/avatar-7.jpg";
import avatar8 from "/images/avatar/avatar-8.jpg";
import product1 from "/images/ecommerce/1.png";
import product2 from "/images/ecommerce/2.png";
import product3 from "/images/ecommerce/3.png";
import product4 from "/images/ecommerce/4.png";
import product5 from "/images/ecommerce/5.png";
import product6 from "/images/ecommerce/6.png";
import product7 from "/images/ecommerce/7.png";
import product8 from "/images/ecommerce/8.png";
import product9 from "/images/ecommerce/9.png";
import product10 from "/images/ecommerce/10.png";
import product11 from "/images/ecommerce/11.png";
import product13 from "/images/ecommerce/13.png";
import product14 from "/images/ecommerce/14.png";
import product15 from "/images/ecommerce/15.png";
import product16 from "/images/ecommerce/16.png";
import product17 from "/images/ecommerce/17.png";
import product18 from "/images/ecommerce/18.png";
import product19 from "/images/ecommerce/19.png";
import product20 from "/images/ecommerce/20.png";
import product23 from "/images/ecommerce/23.png";
import product24 from "/images/ecommerce/24.png";

export const data = [
  {
    responsive_id: "",
    id: 95,
    avatar: avatar2,
    full_name: "Edwina Ebsworth",
    post: "Human Resources Assistant",
    email: "eebsworth2m@sbwire.com",
    city: "Puzi",
    start_date: "09/27/2018",
    salary: 19586.23,
    age: "27",
    experience: "2 Years",
    status: 1,
  },
  {
    responsive_id: "",
    id: 1,
    avatar: avatar8,
    full_name: "Korrie O'Crevy",
    post: "Nuclear Power Engineer",
    email: "kocrevy0@thetimes.co.uk",
    city: "Krasnosilka",
    start_date: "09/23/2016",
    salary: 23896.35,
    age: "61",
    experience: "1 Year",
    status: 2,
  },
  {
    responsive_id: "",
    id: 7,
    avatar: "",
    full_name: "Eileen Diehn",
    post: "Environmental Specialist",
    email: "ediehn6@163.com",
    city: "Lampuyang",
    start_date: "10/15/2017",
    salary: 18991.67,
    age: "59",
    experience: "9 Years",
    status: 3,
  },
  {
    responsive_id: "",
    id: 11,
    avatar: "",
    full_name: "De Falloon",
    post: "Sales Representative",
    email: "dfalloona@ifeng.com",
    city: "Colima",
    start_date: "06/12/2018",
    salary: 19252.12,
    age: "30",
    experience: "0 Year",
    status: 4,
  },
  {
    responsive_id: "",
    id: 3,
    avatar: avatar7,
    full_name: "Stella Ganderton",
    post: "Operator",
    email: "sganderton2@tuttocitta.it",
    city: "Golcowa",
    start_date: "03/24/2018",
    salary: 13076.28,
    age: "66",
    experience: "6 Years",
    status: 5,
  },
  {
    responsive_id: "",
    id: 5,
    avatar: "",
    full_name: "Harmonia Nisius",
    post: "Senior Cost Accountant",
    email: "hnisius4@gnu.org",
    city: "Lucan",
    start_date: "08/25/2017",
    salary: 10909.52,
    age: "33",
    experience: "3 Years",
    status: 2,
  },
  {
    responsive_id: "",
    id: 6,
    avatar: "",
    full_name: "Genevra Honeywood",
    post: "Geologist",
    email: "ghoneywood5@narod.ru",
    city: "Maofan",
    start_date: "06/01/2017",
    salary: 17803.8,
    age: "61",
    experience: "1 Year",
    status: 1,
  },
  {
    responsive_id: "",
    id: 4,
    avatar: avatar8,
    full_name: "Dorolice Crossman",
    post: "Cost Accountant",
    email: "dcrossman3@google.co.jp",
    city: "Paquera",
    start_date: "12/03/2017",
    salary: 12336.17,
    age: "22",
    experience: "2 Years",
    status: 2,
  },
  {
    responsive_id: "",
    id: 8,
    avatar: avatar7,
    full_name: "Richardo Aldren",
    post: "Senior Sales Associate",
    email: "raldren7@mtv.com",
    city: "Skoghall",
    start_date: "11/05/2016",
    salary: 19230.13,
    age: "55",
    experience: "5 Years",
    status: 3,
  },
  {
    responsive_id: "",
    id: 9,
    avatar: avatar2,
    full_name: "Allyson Moakler",
    post: "Safety Technician",
    email: "amoakler8@shareasale.com",
    city: "Mogilany",
    start_date: "12/29/2018",
    salary: 11677.32,
    age: "39",
    experience: "9 Years",
    status: 5,
  },
  {
    responsive_id: "",
    id: 10,
    avatar: avatar7,
    full_name: "Merline Penhalewick",
    post: "Junior Executive",
    email: "mpenhalewick9@php.net",
    city: "Kanuma",
    start_date: "04/19/2019",
    salary: 15939.52,
    age: "23",
    experience: "3 Years",
    status: 2,
  },
  {
    responsive_id: "",
    id: 12,
    avatar: "",
    full_name: "Cyrus Gornal",
    post: "Senior Sales Associate",
    email: "cgornalb@fda.gov",
    city: "Boro Utara",
    start_date: "12/09/2017",
    salary: 16745.47,
    age: "22",
    experience: "2 Years",
    status: 4,
  },
  {
    responsive_id: "",
    id: 13,
    avatar: "",
    full_name: "Tallou Balf",
    post: "Staff Accountant",
    email: "tbalfc@sina.com.cn",
    city: "Siliana",
    start_date: "01/21/2016",
    salary: 15488.53,
    age: "36",
    experience: "6 Years",
    status: 4,
  },
  {
    responsive_id: "",
    id: 14,
    avatar: "",
    full_name: "Othilia Extill",
    post: "Associate Professor",
    email: "oextilld@theatlantic.com",
    city: "Brzyska",
    start_date: "02/01/2016",
    salary: 18442.34,
    age: "43",
    experience: "3 Years",
    status: 2,
  },
  {
    responsive_id: "",
    id: 15,
    avatar: "",
    full_name: "Wilmar Bourton",
    post: "Administrative Assistant",
    email: "wbourtone@sakura.ne.jp",
    city: "Bích Động",
    start_date: "04/25/2018",
    salary: 13304.45,
    age: "19",
    experience: "9 Years",
    status: 5,
  },
  {
    responsive_id: "",
    id: 16,
    avatar: avatar4,
    full_name: "Robinson Brazenor",
    post: "General Manager",
    email: "rbrazenorf@symantec.com",
    city: "Gendiwu",
    start_date: "12/23/2017",
    salary: 11953.08,
    age: "66",
    experience: "6 Years",
    status: 5,
  },
  {
    responsive_id: "",
    id: 17,
    avatar: "",
    full_name: "Nadia Bettenson",
    post: "Environmental Tech",
    email: "nbettensong@joomla.org",
    city: "Chabařovice",
    start_date: "07/11/2018",
    salary: 20484.44,
    age: "64",
    experience: "4 Years",
    status: 1,
  },
  {
    responsive_id: "",
    id: 18,
    avatar: "",
    full_name: "Titus Hayne",
    post: "Web Designer",
    email: "thayneh@kickstarter.com",
    city: "Yangon",
    start_date: "05/25/2019",
    salary: 16871.48,
    age: "59",
    experience: "9 Years",
    status: 1,
  },
  {
    responsive_id: "",
    id: 19,
    avatar: avatar4,
    full_name: "Roxie Huck",
    post: "Administrative Assistant",
    email: "rhucki@ed.gov",
    city: "Polýkastro",
    start_date: "04/04/2019",
    salary: 19653.56,
    age: "41",
    experience: "1 Year",
    status: 4,
  },
  {
    responsive_id: "",
    id: 20,
    avatar: avatar7,
    full_name: "Latashia Lewtey",
    post: "Actuary",
    email: "llewteyj@sun.com",
    city: "Hougong",
    start_date: "08/03/2017",
    salary: 18303.87,
    age: "35",
    experience: "5 Years",
    status: 1,
  },
  {
    responsive_id: "",
    id: 21,
    avatar: "",
    full_name: "Natalina Tyne",
    post: "Software Engineer",
    email: "ntynek@merriam-webster.com",
    city: "Yanguan",
    start_date: "03/16/2019",
    salary: 15256.4,
    age: "30",
    experience: "0 Year",
    status: 2,
  },
  {
    responsive_id: "",
    id: 22,
    avatar: "",
    full_name: "Faun Josefsen",
    post: "Analog Circuit Design manager",
    email: "fjosefsenl@samsung.com",
    city: "Wengyang",
    start_date: "07/08/2017",
    salary: 11209.16,
    age: "40",
    experience: "0 Year",
    status: 3,
  },
  {
    responsive_id: "",
    id: 23,
    avatar: avatar7,
    full_name: "Rosmunda Steed",
    post: "Assistant Media Planner",
    email: "rsteedm@xing.com",
    city: "Manzanares",
    start_date: "12/23/2017",
    salary: 13778.34,
    age: "21",
    experience: "1 Year",
    status: 5,
  },
  {
    responsive_id: "",
    id: 24,
    avatar: "",
    full_name: "Scott Jiran",
    post: "Graphic Designer",
    email: "sjirann@simplemachines.org",
    city: "Pinglin",
    start_date: "05/26/2016",
    salary: 23081.71,
    age: "23",
    experience: "3 Years",
    status: 1,
  },
  {
    responsive_id: "",
    id: 25,
    avatar: "",
    full_name: "Carmita Medling",
    post: "Accountant",
    email: "cmedlingo@hp.com",
    city: "Bourges",
    start_date: "07/31/2019",
    salary: 13602.24,
    age: "47",
    experience: "7 Years",
    status: 3,
  },
  {
    responsive_id: "",
    id: 26,
    avatar: avatar2,
    full_name: "Morgen Benes",
    post: "Senior Sales Associate",
    email: "mbenesp@ted.com",
    city: "Cà Mau",
    start_date: "04/10/2016",
    salary: 16969.63,
    age: "42",
    experience: "2 Years",
    status: 4,
  },
  {
    responsive_id: "",
    id: 27,
    avatar: "",
    full_name: "Onfroi Doughton",
    post: "Civil Engineer",
    email: "odoughtonq@aboutads.info",
    city: "Utrecht (stad)",
    start_date: "09/29/2018",
    salary: 23796.62,
    age: "28",
    experience: "8 Years",
    status: 3,
  },
  {
    responsive_id: "",
    id: 28,
    avatar: "",
    full_name: "Kliment McGinney",
    post: "Chief Design Engineer",
    email: "kmcginneyr@paginegialle.it",
    city: "Xiaocheng",
    start_date: "07/09/2018",
    salary: 24027.81,
    age: "28",
    experience: "8 Years",
    status: 4,
  },
  {
    responsive_id: "",
    id: 29,
    avatar: "",
    full_name: "Devin Bridgland",
    post: "Tax Accountant",
    email: "dbridglands@odnoklassniki.ru",
    city: "Baoli",
    start_date: "07/17/2016",
    salary: 13508.15,
    age: "48",
    experience: "8 Years",
    status: 3,
  },
  {
    responsive_id: "",
    id: 30,
    avatar: avatar6,
    full_name: "Gilbert McFade",
    post: "Biostatistician",
    email: "gmcfadet@irs.gov",
    city: "Deje",
    start_date: "08/28/2018",
    salary: 21632.3,
    age: "20",
    experience: "0 Year",
    status: 2,
  },
  {
    responsive_id: "",
    id: 31,
    avatar: "",
    full_name: "Teressa Bleakman",
    post: "Senior Editor",
    email: "tbleakmanu@phpbb.com",
    city: "Žebrák",
    start_date: "09/03/2016",
    salary: 24875.41,
    age: "37",
    experience: "7 Years",
    status: 5,
  },
  {
    responsive_id: "",
    id: 32,
    avatar: "",
    full_name: "Marcelia Alleburton",
    post: "Safety Technician",
    email: "malleburtonv@amazon.com",
    city: "Basail",
    start_date: "06/02/2016",
    salary: 23888.98,
    age: "53",
    experience: "3 Years",
    status: 2,
  },
  {
    responsive_id: "",
    id: 33,
    avatar: avatar7,
    full_name: "Aili De Coursey",
    post: "Environmental Specialist",
    email: "adew@etsy.com",
    city: "Łazy",
    start_date: "09/30/2016",
    salary: 14082.44,
    age: "27",
    experience: "7 Years",
    status: 5,
  },
  {
    responsive_id: "",
    id: 34,
    avatar: avatar6,
    full_name: "Charlton Chatres",
    post: "Analyst Programmer",
    email: "cchatresx@goo.gl",
    city: "Reguengos de Monsaraz",
    start_date: "04/07/2016",
    salary: 21386.52,
    age: "22",
    experience: "2 Years",
    status: 3,
  },
  {
    responsive_id: "",
    id: 35,
    avatar: avatar1,
    full_name: "Nat Hugonnet",
    post: "Financial Advisor",
    email: "nhugonnety@wufoo.com",
    city: "Pimentel",
    start_date: "09/11/2019",
    salary: 13835.97,
    age: "46",
    experience: "6 Years",
    status: 4,
  },
  {
    responsive_id: "",
    id: 36,
    avatar: "",
    full_name: "Lorine Hearsum",
    post: "Payment Adjustment Coordinator",
    email: "lhearsumz@google.co.uk",
    city: "Shuiying",
    start_date: "03/05/2019",
    salary: 22093.91,
    age: "47",
    experience: "7 Years",
    status: 4,
  },
  {
    responsive_id: "",
    id: 37,
    avatar: avatar5,
    full_name: "Sheila-kathryn Haborn",
    post: "Environmental Specialist",
    email: "shaborn10@about.com",
    city: "Lewolang",
    start_date: "11/10/2018",
    salary: 24624.23,
    age: "51",
    experience: "1 Year",
    status: 3,
  },
  {
    responsive_id: "",
    id: 38,
    avatar: avatar3,
    full_name: "Alma Harvatt",
    post: "Administrative Assistant",
    email: "aharvatt11@addtoany.com",
    city: "Ulundi",
    start_date: "11/04/2016",
    salary: 21782.82,
    age: "41",
    experience: "1 Year",
    status: 1,
  },
  {
    responsive_id: "",
    id: 39,
    avatar: avatar2,
    full_name: "Beatrix Longland",
    post: "VP Quality Control",
    email: "blongland12@gizmodo.com",
    city: "Damu",
    start_date: "07/18/2016",
    salary: 22794.6,
    age: "62",
    experience: "2 Years",
    status: 2,
  },
  {
    responsive_id: "",
    id: 40,
    avatar: avatar4,
    full_name: "Hammad Condell",
    post: "Project Manager",
    email: "hcondell13@tiny.cc",
    city: "Bulung’ur",
    start_date: "11/04/2018",
    salary: 10872.83,
    age: "37",
    experience: "7 Years",
    status: 4,
  },
  {
    responsive_id: "",
    id: 41,
    avatar: "",
    full_name: "Parker Bice",
    post: "Technical Writer",
    email: "pbice14@ameblo.jp",
    city: "Shanlian",
    start_date: "03/02/2016",
    salary: 17471.92,
    age: "65",
    experience: "5 Years",
    status: 5,
  },
  {
    responsive_id: "",
    id: 42,
    avatar: "",
    full_name: "Lowrance Orsi",
    post: "Biostatistician",
    email: "lorsi15@wp.com",
    city: "Dengteke",
    start_date: "12/10/2018",
    salary: 24719.51,
    age: "64",
    experience: "4 Years",
    status: 1,
  },
  {
    responsive_id: "",
    id: 43,
    avatar: avatar8,
    full_name: "Ddene Chaplyn",
    post: "Environmental Tech",
    email: "dchaplyn16@nymag.com",
    city: "Lattes",
    start_date: "01/23/2019",
    salary: 11958.33,
    age: "38",
    experience: "8 Years",
    status: 2,
  },
  {
    responsive_id: "",
    id: 44,
    avatar: "",
    full_name: "Washington Bygraves",
    post: "Human Resources Manager",
    email: "wbygraves17@howstuffworks.com",
    city: "Zlaté Hory",
    start_date: "09/07/2016",
    salary: 10552.43,
    age: "37",
    experience: "7 Years",
    status: 1,
  },
  {
    responsive_id: "",
    id: 45,
    avatar: avatar7,
    full_name: "Meghann Bodechon",
    post: "Operator",
    email: "mbodechon18@1und1.de",
    city: "Itō",
    start_date: "07/23/2018",
    salary: 23024.28,
    age: "61",
    experience: "1 Year",
    status: 4,
  },
  {
    responsive_id: "",
    id: 46,
    avatar: avatar1,
    full_name: "Moshe De Ambrosis",
    post: "Recruiting Manager",
    email: "mde19@purevolume.com",
    city: "San Diego",
    start_date: "02/10/2018",
    salary: 10409.9,
    age: "47",
    experience: "7 Years",
    status: 5,
  },
  {
    responsive_id: "",
    id: 47,
    avatar: avatar4,
    full_name: "Had Chatelot",
    post: "Cost Accountant",
    email: "hchatelot1a@usatoday.com",
    city: "Mercedes",
    start_date: "11/23/2016",
    salary: 11446.3,
    age: "64",
    experience: "4 Years",
    status: 4,
  },
  {
    responsive_id: "",
    id: 48,
    avatar: "",
    full_name: "Georgia McCrum",
    post: "Registered Nurse",
    email: "gmccrum1b@icio.us",
    city: "Nggalak",
    start_date: "04/19/2018",
    salary: 14002.31,
    age: "63",
    experience: "3 Years",
    status: 1,
  },
  {
    responsive_id: "",
    id: 49,
    avatar: avatar5,
    full_name: "Krishnah Stilldale",
    post: "VP Accounting",
    email: "kstilldale1c@chronoengine.com",
    city: "Slavs’ke",
    start_date: "03/18/2017",
    salary: 10704.29,
    age: "56",
    experience: "6 Years",
    status: 1,
  },
  {
    responsive_id: "",
    id: 50,
    avatar: avatar4,
    full_name: "Mario Umbert",
    post: "Research Assistant",
    email: "mumbert1d@digg.com",
    city: "Chorotis",
    start_date: "05/13/2019",
    salary: 21813.54,
    age: "43",
    experience: "3 Years",
    status: 1,
  },
  {
    responsive_id: "",
    id: 51,
    avatar: "",
    full_name: "Edvard Dixsee",
    post: "Graphic Designer",
    email: "edixsee1e@unblog.fr",
    city: "Rancharia",
    start_date: "04/23/2019",
    salary: 18053.11,
    age: "46",
    experience: "6 Years",
    status: 3,
  },
  {
    responsive_id: "",
    id: 52,
    avatar: avatar7,
    full_name: "Tammie Davydoch",
    post: "VP Quality Control",
    email: "tdavydoch1f@examiner.com",
    city: "Mamedkala",
    start_date: "04/19/2016",
    salary: 17617.08,
    age: "47",
    experience: "7 Years",
    status: 3,
  },
  {
    responsive_id: "",
    id: 53,
    avatar: "",
    full_name: "Benito Rodolico",
    post: "Safety Technician",
    email: "brodolico1g@sciencedirect.com",
    city: "Wonosobo",
    start_date: "10/06/2018",
    salary: 18866.55,
    age: "21",
    experience: "1 Year",
    status: 5,
  },
  {
    responsive_id: "",
    id: 54,
    avatar: "",
    full_name: "Marco Pennings",
    post: "Compensation Analyst",
    email: "mpennings1h@bizjournals.com",
    city: "Umag",
    start_date: "06/15/2017",
    salary: 13722.18,
    age: "30",
    experience: "0 Year",
    status: 3,
  },
  {
    responsive_id: "",
    id: 55,
    avatar: "",
    full_name: "Tommie O'Corr",
    post: "Quality Engineer",
    email: "tocorr1i@nyu.edu",
    city: "Olhos de Água",
    start_date: "09/26/2018",
    salary: 15228.8,
    age: "51",
    experience: "1 Year",
    status: 1,
  },
  {
    responsive_id: "",
    id: 56,
    avatar: avatar1,
    full_name: "Cybill Poyle",
    post: "Cost Accountant",
    email: "cpoyle1j@amazon.com",
    city: "Hamm",
    start_date: "01/03/2016",
    salary: 13951.96,
    age: "29",
    experience: "9 Years",
    status: 1,
  },
  {
    responsive_id: "",
    id: 57,
    avatar: avatar6,
    full_name: "Norry Stoller",
    post: "Human Resources Manager",
    email: "nstoller1k@noaa.gov",
    city: "Ruukki",
    start_date: "02/04/2018",
    salary: 15100.0,
    age: "27",
    experience: "7 Years",
    status: 4,
  },
  {
    responsive_id: "",
    id: 58,
    avatar: "",
    full_name: "Wendi Somerlie",
    post: "Systems Administrator",
    email: "wsomerlie1l@accuweather.com",
    city: "Meicheng",
    start_date: "04/22/2016",
    salary: 20023.52,
    age: "28",
    experience: "9 Years",
    status: 5,
  },
  {
    responsive_id: "",
    id: 59,
    avatar: "",
    full_name: "Ferdie Georgeon",
    post: "Geologist",
    email: "fgeorgeon1m@nhs.uk",
    city: "Tanahbeureum",
    start_date: "04/08/2019",
    salary: 12630.26,
    age: "28",
    experience: "1 Year",
    status: 2,
  },
  {
    responsive_id: "",
    id: 60,
    avatar: "",
    full_name: "Jules Auten",
    post: "Desktop Support Technician",
    email: "jauten1n@foxnews.com",
    city: "Mojo",
    start_date: "08/13/2019",
    salary: 13870.62,
    age: "48",
    experience: "5 Years",
    status: 4,
  },
  {
    responsive_id: "",
    id: 61,
    avatar: avatar3,
    full_name: "Nichole Dacres",
    post: "Mechanical Systems Engineer",
    email: "ndacres1o@apache.org",
    city: "Kimanuit",
    start_date: "11/06/2017",
    salary: 18220.51,
    age: "20",
    experience: "0 Year",
    status: 3,
  },
  {
    responsive_id: "",
    id: 62,
    avatar: avatar1,
    full_name: "Holly Edgworth",
    post: "Junior Executive",
    email: "hedgworth1p@craigslist.org",
    city: "Pedreira",
    start_date: "08/05/2017",
    salary: 13999.88,
    age: "37",
    experience: "0 Year",
    status: 5,
  },
  {
    responsive_id: "",
    id: 63,
    avatar: avatar7,
    full_name: "Henriette Croft",
    post: "Food Chemist",
    email: "hcroft1q@desdev.cn",
    city: "Taizhou",
    start_date: "09/12/2019",
    salary: 11049.79,
    age: "53",
    experience: "1 Year",
    status: 5,
  },
  {
    responsive_id: "",
    id: 64,
    avatar: "",
    full_name: "Annetta Glozman",
    post: "Staff Accountant",
    email: "aglozman1r@storify.com",
    city: "Pendawanbaru",
    start_date: "08/25/2017",
    salary: 10745.32,
    age: "27",
    experience: "3 Years",
    status: 5,
  },
  {
    responsive_id: "",
    id: 65,
    avatar: "",
    full_name: "Cletis Cervantes",
    post: "Health Coach",
    email: "ccervantes1s@de.vu",
    city: "Solnechnyy",
    start_date: "05/24/2018",
    salary: 24769.08,
    age: "22",
    experience: "7 Years",
    status: 1,
  },
  {
    responsive_id: "",
    id: 66,
    avatar: avatar7,
    full_name: "Christos Kiley",
    post: "Geologist",
    email: "ckiley1t@buzzfeed.com",
    city: "El Bolsón",
    start_date: "02/27/2019",
    salary: 16053.15,
    age: "46",
    experience: "2 Years",
    status: 1,
  },
  {
    responsive_id: "",
    id: 67,
    avatar: avatar7,
    full_name: "Silvain Siebert",
    post: "VP Sales",
    email: "ssiebert1u@domainmarket.com",
    city: "Cadiz",
    start_date: "09/23/2017",
    salary: 23347.17,
    age: "47",
    experience: "8 Years",
    status: 5,
  },
  {
    responsive_id: "",
    id: 68,
    avatar: "",
    full_name: "Sharla Ibberson",
    post: "Payment Adjustment Coordinator",
    email: "sibberson1v@virginia.edu",
    city: "Lamam",
    start_date: "11/01/2016",
    salary: 15658.4,
    age: "51",
    experience: "8 Years",
    status: 1,
  },
  {
    responsive_id: "",
    id: 69,
    avatar: avatar7,
    full_name: "Ripley Rentcome",
    post: "Physical Therapy Assistant",
    email: "rrentcome1w@youtu.be",
    city: "Dashkawka",
    start_date: "07/15/2018",
    salary: 15396.66,
    age: "41",
    experience: "8 Years",
    status: 2,
  },
  {
    responsive_id: "",
    id: 70,
    avatar: "",
    full_name: "Chrisse Birrane",
    post: "Chemical Engineer",
    email: "cbirrane1x@google.com.br",
    city: "Las Toscas",
    start_date: "05/22/2016",
    salary: 15823.4,
    age: "62",
    experience: "0 Year",
    status: 5,
  },
  {
    responsive_id: "",
    id: 71,
    avatar: "",
    full_name: "Georges Tesyro",
    post: "Human Resources Manager",
    email: "gtesyro1y@last.fm",
    city: "Gabao",
    start_date: "01/27/2019",
    salary: 19051.25,
    age: "37",
    experience: "7 Years",
    status: 1,
  },
  {
    responsive_id: "",
    id: 72,
    avatar: "",
    full_name: "Bondon Hazard",
    post: "Geological Engineer",
    email: "bhazard1z@over-blog.com",
    city: "Llano de Piedra",
    start_date: "01/17/2019",
    salary: 11632.84,
    age: "65",
    experience: "3 Years",
    status: 4,
  },
  {
    responsive_id: "",
    id: 73,
    avatar: avatar4,
    full_name: "Aliza MacElholm",
    post: "VP Sales",
    email: "amacelholm20@printfriendly.com",
    city: "Sosnovyy Bor",
    start_date: "11/17/2017",
    salary: 16741.31,
    age: "64",
    experience: "7 Years",
    status: 2,
  },
  {
    responsive_id: "",
    id: 74,
    avatar: avatar2,
    full_name: "Lucas Witherdon",
    post: "Senior Quality Engineer",
    email: "lwitherdon21@storify.com",
    city: "Staré Křečany",
    start_date: "09/26/2016",
    salary: 19387.76,
    age: "38",
    experience: "2 Years",
    status: 3,
  },
  {
    responsive_id: "",
    id: 75,
    avatar: "",
    full_name: "Pegeen Peasegod",
    post: "Web Designer",
    email: "ppeasegod22@slideshare.net",
    city: "Keda",
    start_date: "05/21/2016",
    salary: 24014.04,
    age: "59",
    experience: "6 Years",
    status: 3,
  },
  {
    responsive_id: "",
    id: 76,
    avatar: "",
    full_name: "Elyn Watkinson",
    post: "Structural Analysis Engineer",
    email: "ewatkinson23@blogspot.com",
    city: "Osan",
    start_date: "09/30/2016",
    salary: 14493.51,
    age: "55",
    experience: "7 Years",
    status: 1,
  },
  {
    responsive_id: "",
    id: 77,
    avatar: avatar8,
    full_name: "Babb Skirving",
    post: "Analyst Programmer",
    email: "bskirving24@cbsnews.com",
    city: "Balky",
    start_date: "09/27/2016",
    salary: 24733.28,
    age: "39",
    experience: "1 Year",
    status: 4,
  },
  {
    responsive_id: "",
    id: 78,
    avatar: "",
    full_name: "Shelli Ondracek",
    post: "Financial Advisor",
    email: "sondracek25@plala.or.jp",
    city: "Aoluguya Ewenke Minzu",
    start_date: "03/28/2016",
    salary: 21922.17,
    age: "23",
    experience: "1 Year",
    status: 3,
  },
  {
    responsive_id: "",
    id: 79,
    avatar: avatar7,
    full_name: "Stanislaw Melloy",
    post: "Sales Associate",
    email: "smelloy26@fastcompany.com",
    city: "Funafuti",
    start_date: "04/13/2017",
    salary: 16944.42,
    age: "30",
    experience: "2 Years",
    status: 2,
  },
  {
    responsive_id: "",
    id: 80,
    avatar: "",
    full_name: "Seamus Eisikovitsh",
    post: "Legal Assistant",
    email: "seisikovitsh27@usgs.gov",
    city: "Cangkringan",
    start_date: "05/28/2018",
    salary: 21963.69,
    age: "22",
    experience: "7 Years",
    status: 1,
  },
  {
    responsive_id: "",
    id: 81,
    avatar: avatar2,
    full_name: "Tammie Wattins",
    post: "Web Designer",
    email: "twattins28@statcounter.com",
    city: "Xilin",
    start_date: "08/07/2018",
    salary: 16049.93,
    age: "36",
    experience: "5 Years",
    status: 2,
  },
  {
    responsive_id: "",
    id: 82,
    avatar: avatar5,
    full_name: "Aila Quailadis",
    post: "Technical Writer",
    email: "aquail29@prlog.org",
    city: "Shuangchahe",
    start_date: "02/11/2018",
    salary: 24137.29,
    age: "43",
    experience: "4 Years",
    status: 4,
  },
  {
    responsive_id: "",
    id: 83,
    avatar: "",
    full_name: "Myrvyn Gilogly",
    post: "Research Associate",
    email: "mgilogly2a@elpais.com",
    city: "Prince Rupert",
    start_date: "05/13/2018",
    salary: 10089.96,
    age: "19",
    experience: "8 Years",
    status: 4,
  },
  {
    responsive_id: "",
    id: 84,
    avatar: avatar4,
    full_name: "Hanna Langthorne",
    post: "Analyst Programmer",
    email: "hlangthorne2b@stumbleupon.com",
    city: "Guaynabo",
    start_date: "11/11/2018",
    salary: 14227.1,
    age: "21",
    experience: "7 Years",
    status: 3,
  },
  {
    responsive_id: "",
    id: 85,
    avatar: "",
    full_name: "Ruby Gimblet",
    post: "Registered Nurse",
    email: "rgimblet2c@1688.com",
    city: "Nanyulinxi",
    start_date: "03/28/2016",
    salary: 19562.59,
    age: "30",
    experience: "1 Year",
    status: 2,
  },
  {
    responsive_id: "",
    id: 86,
    avatar: avatar4,
    full_name: "Louis Paszak",
    post: "Programmer",
    email: "lpaszak2d@behance.net",
    city: "Chiscas",
    start_date: "04/25/2016",
    salary: 17178.86,
    age: "51",
    experience: "7 Years",
    status: 5,
  },
  {
    responsive_id: "",
    id: 87,
    avatar: "",
    full_name: "Glennie Riolfi",
    post: "Computer Systems Analyst",
    email: "griolfi2e@drupal.org",
    city: "Taung",
    start_date: "06/18/2018",
    salary: 15089.83,
    age: "29",
    experience: "4 Years",
    status: 3,
  },
  {
    responsive_id: "",
    id: 88,
    avatar: "",
    full_name: "Jemimah Morgan",
    post: "Staff Accountant",
    email: "jmorgan2f@nifty.com",
    city: "La Esperanza",
    start_date: "01/17/2016",
    salary: 18330.72,
    age: "27",
    experience: "3 Years",
    status: 1,
  },
  {
    responsive_id: "",
    id: 89,
    avatar: avatar8,
    full_name: "Talya Brandon",
    post: "Food Chemist",
    email: "tbrandon2g@ucoz.com",
    city: "Zaječar",
    start_date: "10/08/2018",
    salary: 16284.64,
    age: "28",
    experience: "6 Years",
    status: 1,
  },
  {
    responsive_id: "",
    id: 90,
    avatar: avatar6,
    full_name: "Renate Shay",
    post: "Recruiter",
    email: "rshay2h@tumblr.com",
    city: "Pueblo Viejo",
    start_date: "03/15/2017",
    salary: 18523.75,
    age: "28",
    experience: "3 Years",
    status: 1,
  },
  {
    responsive_id: "",
    id: 91,
    avatar: "",
    full_name: "Julianne Bartosik",
    post: "Senior Cost Accountant",
    email: "jbartosik2i@state.gov",
    city: "Botlhapatlou",
    start_date: "02/06/2017",
    salary: 17607.66,
    age: "48",
    experience: "6 Years",
    status: 3,
  },
  {
    responsive_id: "",
    id: 92,
    avatar: avatar3,
    full_name: "Yvonne Emberton",
    post: "Recruiter",
    email: "yemberton2j@blog.com",
    city: "Nagcarlan",
    start_date: "02/13/2017",
    salary: 17550.18,
    age: "20",
    experience: "1 Year",
    status: 4,
  },
  {
    responsive_id: "",
    id: 93,
    avatar: avatar5,
    full_name: "Danya Faichnie",
    post: "Social Worker",
    email: "dfaichnie2k@weather.com",
    city: "Taling",
    start_date: "07/29/2019",
    salary: 18469.35,
    age: "37",
    experience: "3 Years",
    status: 4,
  },
  {
    responsive_id: "",
    id: 94,
    avatar: "",
    full_name: "Ronica Hasted",
    post: "Software Consultant",
    email: "rhasted2l@hexun.com",
    city: "Gangkou",
    start_date: "07/04/2019",
    salary: 24866.66,
    age: "53",
    experience: "7 Years",
    status: 4,
  },
  {
    responsive_id: "",
    id: 96,
    avatar: "",
    full_name: "Alaric Beslier",
    post: "Tax Accountant",
    email: "abeslier2n@zimbio.com",
    city: "Ocucaje",
    start_date: "04/16/2017",
    salary: 19366.53,
    age: "22",
    experience: "8 Years",
    status: 4,
  },
  {
    responsive_id: "",
    id: 2,
    avatar: avatar1,
    full_name: "Bailie Coulman",
    post: "VP Quality Control",
    email: "bcoulman1@yolasite.com",
    city: "Hinigaran",
    start_date: "05/20/2018",
    salary: 13633.69,
    age: "63",
    experience: "3 Years",
    status: 2,
  },
  {
    responsive_id: "",
    id: 97,
    avatar: "",
    full_name: "Reina Peckett",
    post: "Quality Control Specialist",
    email: "rpeckett2o@timesonline.co.uk",
    city: "Anyang",
    start_date: "05/20/2018",
    salary: 16619.4,
    age: "46",
    experience: "8 Years",
    status: 4,
  },
  {
    responsive_id: "",
    id: 98,
    avatar: avatar7,
    full_name: "Olivette Gudgin",
    post: "Paralegal",
    email: "ogudgin2p@gizmodo.com",
    city: "Fujinomiya",
    start_date: "04/09/2019",
    salary: 15211.6,
    age: "47",
    experience: "8 Years",
    status: 2,
  },
  {
    responsive_id: "",
    id: 99,
    avatar: avatar8,
    full_name: "Evangelina Carnock",
    post: "Cost Accountant",
    email: "ecarnock2q@washington.edu",
    city: "Doushaguan",
    start_date: "01/26/2017",
    salary: 23704.82,
    age: "51",
    experience: "0 Year",
    status: 4,
  },
  {
    responsive_id: "",
    id: 100,
    avatar: "",
    full_name: "Glyn Giacoppo",
    post: "Software Test Engineer",
    email: "ggiacoppo2r@apache.org",
    city: "Butha-Buthe",
    start_date: "04/15/2017",
    salary: 24973.48,
    age: "41",
    experience: "7 Years",
    status: 2,
  },
];

export const productList = ref([
  {
    product: {
      id: 19,
      name: "OnePlus 7 Pro ",
      slug: "one-plus-7-pro-19",
      brand: "Philips",
      category: "Smart Phone",
      price: 14.99,
      image: product9,
      hasFreeShipping: false,
      rating: 4,
      description:
        "The OnePlus 7 Pro features a brand new design, with a glass back and front and curved sides. The phone feels\n    very premium but\u2019s it\u2019s also very heavy. The Nebula Blue variant looks slick but it\u2019s quite slippery, which\n    makes single-handed use a real challenge. It has a massive 6.67-inch \u2018Fluid AMOLED\u2019 display with a QHD+\n    resolution, 90Hz refresh rate and support for HDR 10+ content. The display produces vivid colours, deep blacks\n    and has good viewing angles.",
    },
    date: "30 Apr 2020",
    buyer: {
      name: "Ana Smith",
      avatar: avatar3,
    },
    payment: {
      total: 984,
      received_payment_status: "Fully Paid",
      paid_amount: 984,
      status: "Completed",
    },
  },
  {
    product: {
      id: 21,
      name: "Google - Google Home",
      slug: "google-google-home-white-slate-fabric-21",
      brand: "Google",
      category: "Google Home",
      price: 129.29,
      image: product7,
      hasFreeShipping: true,
      rating: 4,
      description:
        "Simplify your everyday life with the Google Home, a voice-activated speaker powered by the Google Assistant. Use\n    voice commands to enjoy music, get answers from Google and manage everyday tasks. Google Home is compatible with\n    Android and iOS operating systems, and can control compatible smart devices such as Chromecast or Nest.",
    },
    date: "11 Jul 2020",
    buyer: {
      name: "Lindsay Green",
      avatar: avatar8,
    },
    payment: {
      total: 1101,
      received_payment_status: "Fully Paid",
      paid_amount: 1101,
      status: "Completed",
    },
  },
  {
    product: {
      id: 17,
      name: "Nike Air Max",
      slug: "72-9301-speaker-wire-harness-adapter-for-most-plymouth-dodge-and-mitsubishi-vehicles-multi-17",
      description:
        "With a bold application of colorblocking inspired by modern art styles, the Nike Air Max 270 React sneaker is constructed with layers of lightweight material to achieve its artful look and comfortable feel.",
      brand: "Nike",
      category: "Shoes",
      price: 81.99,
      image: product11,
      hasFreeShipping: true,
      rating: 5,
    },
    date: "06 Jan 2021",
    buyer: {
      name: "Ethan Lee",
      avatar: avatar1,
    },
    payment: {
      total: 726,
      received_payment_status: "Partially Paid",
      paid_amount: 126,
      status: "Confirmed",
    },
  },
  {
    product: {
      id: 2,
      name: "Bose Frames Tenor",
      slug: "bose-frames-tenor-rectangular-polarized-bluetooth-audio-sunglasses-2",
      description:
        "Redesigned for luxury \u2014 Thoughtfully refined and strikingly elegant, the latest Bose sunglasses blend enhanced features and designs for an elevated way to listen",
      brand: "Bose",
      category: "Glass",
      price: 249,
      image: product2,
      hasFreeShipping: false,
      rating: 4,
    },
    date: "21 Aug 2020",
    buyer: {
      name: "Scott Miller",
      avatar: avatar7,
    },
    payment: {
      total: 646,
      received_payment_status: "Partially Paid",
      paid_amount: 345,
      status: "Confirmed",
    },
  },
  {
    product: {
      id: 25,
      name: "Apple iMac 27-inch",
      slug: "apple-i-mac-27-inch-25",
      brand: "Apple",
      category: "IMac",
      price: 999.99,
      image: product3,
      hasFreeShipping: true,
      rating: 4,
      description:
        "The all-in-one for all. If you can dream it, you can do it on iMac. It\u2019s beautifully & incredibly intuitive and\n    packed with tools that let you take any idea to the next level. And the new 27-inch model elevates the\n    experience in way, with faster processors and graphics, expanded memory and storage, enhanced audio and video\n    capabilities, and an even more stunning Retina 5K display. It\u2019s the desktop that does it all \u2014 better and faster\n    than ever.",
    },
    date: "21 Aug 2020",
    buyer: {
      name: "Brandon Brooks",
      avatar: avatar5,
    },
    payment: {
      total: 1005,
      received_payment_status: "Partially Paid",
      paid_amount: 21,
      status: "Confirmed",
    },
  },
  {
    product: {
      id: 12,
      name: "Adidas Mens Tech Response Shoes",
      slug: "adidas-mens-tech-response-shoes-12",
      description:
        "Comfort + performance.  Designed with materials that are durable, lightweight and extremely comfortable. Core performance delivers the perfect mix of fit, style and all-around performance.",
      brand: "Adidas",
      category: "Shoes",
      price: 54.59,
      image: product16,
      hasFreeShipping: false,
      rating: 5,
    },
    date: "10 Mar 2021",
    buyer: {
      name: "Henry Mann",
      avatar: avatar6,
    },
    payment: {
      total: 1114,
      received_payment_status: "Partially Paid",
      paid_amount: 814,
      status: "Confirmed",
    },
  },
  {
    product: {
      id: 25,
      name: "Apple iMac 27-inch",
      slug: "apple-i-mac-27-inch-25",
      brand: "Apple",
      category: "IMac",
      price: 999.99,
      image: product3,
      hasFreeShipping: true,
      rating: 4,
      description:
        "The all-in-one for all. If you can dream it, you can do it on iMac. It\u2019s beautifully & incredibly intuitive and\n    packed with tools that let you take any idea to the next level. And the new 27-inch model elevates the\n    experience in way, with faster processors and graphics, expanded memory and storage, enhanced audio and video\n    capabilities, and an even more stunning Retina 5K display. It\u2019s the desktop that does it all \u2014 better and faster\n    than ever.",
    },
    date: "21 Aug 2020",
    buyer: {
      name: "Brandon Brooks",
      avatar: avatar5,
    },
    payment: {
      total: 1005,
      received_payment_status: "Partially Paid",
      paid_amount: 21,
      status: "Confirmed",
    },
  },
  {
    product: {
      id: 24,
      name: "OneOdio A71 Wired Headphones",
      slug: "one-odio-a71-wired-headphones-24",
      brand: "OneOdio",
      category: "Headphone",
      price: 49.99,
      image: product4,
      hasFreeShipping: true,
      rating: 3,
      description:
        "Omnidirectional detachable boom mic upgrades the headphones into a professional headset for gaming, business,\n    podcasting and taking calls on the go. Better pick up your voice. Control most electric devices through voice\n    activation, or schedule a ride with Uber and order a pizza. OneOdio A71 Wired Headphones voice-controlled device\n    turns any home into a smart device on a smartphone or tablet.",
    },
    date: "12 Nov 2020",
    buyer: {
      name: "Grant Wright",
      avatar: avatar2,
    },
    payment: {
      total: 207,
      received_payment_status: "Fully Paid",
      paid_amount: 207,
      status: "Completed",
    },
  },
  {
    product: {
      id: 20,
      name: "Sony 4K Ultra HD LED TV ",
      slug: "sony-4-k-ultra-hd-led-tv-20",
      brand: "Apple",
      category: "Smart TV",
      price: 7999.99,
      image: product8,
      hasFreeShipping: false,
      rating: 5,
      description:
        "Sony 4K Ultra HD LED TV has 4K HDR Support. The TV provides clear visuals and provides distinct sound quality\n    and an immersive experience. This TV has Yes HDMI ports & Yes USB ports. Connectivity options included are HDMI.\n    You can connect various gadgets such as your laptop using the HDMI port. The TV comes with a 1 Year warranty.",
    },
    date: "19 Apr 2021",
    buyer: {
      name: "Amanda Sanchez",
      avatar: avatar2,
    },
    payment: {
      total: 1119,
      received_payment_status: "Fully Paid",
      paid_amount: 1119,
      status: "Completed",
    },
  },
  {
    product: {
      id: 23,
      name: "Apple - MacBook Air\u00AE",
      slug: "apple-mac-book-air-latest-model-13-3-display-silver-23",
      brand: "Apple",
      category: "Mac",
      price: 999.99,
      image: product5,
      hasFreeShipping: false,
      rating: 4,
      description:
        "MacBook Air is a thin, lightweight laptop from Apple. MacBook Air features up to 8GB of memory, a\n    fifth-generation Intel Core processor, Thunderbolt 2, great built-in apps, and all-day battery life.1 Its thin,\n    light, and durable enough to take everywhere you go-and powerful enough to do everything once you get there,\n better.",
    },
    date: "25 Dec 2020",
    buyer: {
      name: "Kathy Estrada",
      avatar: avatar2,
    },
    payment: {
      total: 1221,
      received_payment_status: "Partially Paid",
      paid_amount: 1025,
      status: "Confirmed",
    },
  },
  {
    product: {
      id: 25,
      name: "Apple iMac 27-inch",
      slug: "apple-i-mac-27-inch-25",
      brand: "Apple",
      category: "IMac",
      price: 999.99,
      image: product3,
      hasFreeShipping: true,
      rating: 4,
      description:
        "The all-in-one for all. If you can dream it, you can do it on iMac. It\u2019s beautifully & incredibly intuitive and\n    packed with tools that let you take any idea to the next level. And the new 27-inch model elevates the\n    experience in way, with faster processors and graphics, expanded memory and storage, enhanced audio and video\n capabilities, and an even more stunning Retina 5K display. It\u2019s the desktop that does it all \u2014 better and faster\n than ever.",
    },
    date: "19 May 2020",
    buyer: {
      name: "William Lopez",
      avatar: avatar2,
    },
    payment: {
      total: 973,
      received_payment_status: "Partially Paid",
      paid_amount: 374,
      status: "Confirmed",
    },
  },
  {
    product: {
      id: 8,
      name: "PlayStation 4 Console",
      slug: "play-station-4-console-8",
      description:
        "All the greatest, games, TV, music and more. Connect with your friends to broadcast and celebrate your epic moments at the press of the Share button to Twitch, YouTube, Facebook and Twitter.",
      brand: "Sony",
      category: "Gaming",
      price: 339.95,
      image: product20,
      hasFreeShipping: false,
      rating: 4,
    },
    date: "27 Mar 2021",
    buyer: {
      name: "Colleen Taylor",
      avatar: avatar2,
    },
    payment: {
      total: 1235,
      received_payment_status: "Fully Paid",
      paid_amount: 1235,
      status: "Completed",
    },
  },
  {
    product: {
      id: 5,
      name: "Toshiba Canvio External Hard Drive",
      slug: "toshiba-canvio-advance-2-tb-portable-external-hard-drive-5",
      description: "Up to 3TB of storage capacity to store your growing files and content",
      brand: "Toshiba",
      category: "Storage Device",
      price: 69.99,
      image: product23,
      hasFreeShipping: true,
      rating: 2,
    },
    date: "21 Jun 2020",
    buyer: {
      name: "Melanie Olson",
      avatar: avatar6,
    },
    payment: {
      total: 780,
      received_payment_status: "Fully Paid",
      paid_amount: 780,
      status: "Completed",
    },
  },
  {
    product: {
      id: 19,
      name: "OnePlus 7 Pro ",
      slug: "one-plus-7-pro-19",
      brand: "Philips",
      category: "Smart Phone",
      price: 14.99,
      image: product9,
      hasFreeShipping: false,
      rating: 4,
      description:
        "The OnePlus 7 Pro features a brand new design, with a glass back and front and curved sides. The phone feels\n    very premium but\u2019s it\u2019s also very heavy. The Nebula Blue variant looks slick but it\u2019s quite slippery, which\n    makes single-handed use a real challenge. It has a massive 6.67-inch \u2018Fluid AMOLED\u2019 display with a QHD+\n    resolution, 90Hz refresh rate and support for HDR 10+ content. The display produces vivid colours, deep blacks\n    and has good viewing angles.",
    },
    date: "28 Jan 2021",
    buyer: {
      name: "Cynthia Cannon",
      avatar: avatar7,
    },
    payment: {
      total: 1073,
      received_payment_status: "Partially Paid",
      paid_amount: 871,
      status: "Confirmed",
    },
  },
  {
    product: {
      id: 23,
      name: "Apple - MacBook Air\u00AE",
      slug: "apple-mac-book-air-latest-model-13-3-display-silver-23",
      brand: "Apple",
      category: "Mac",
      price: 999.99,
      image: product5,
      hasFreeShipping: false,
      rating: 4,
      description:
        "MacBook Air is a thin, lightweight laptop from Apple. MacBook Air features up to 8GB of memory, a\n    fifth-generation Intel Core processor, Thunderbolt 2, great built-in apps, and all-day battery life.1 Its thin,\n    light, and durable enough to take everywhere you go-and powerful enough to do everything once you get there,\n better.",
    },
    date: "20 Aug 2020",
    buyer: {
      name: "David Archer",
      avatar: avatar5,
    },
    payment: {
      total: 224,
      received_payment_status: "Fully Paid",
      paid_amount: 224,
      status: "Completed",
    },
  },
  {
    product: {
      id: 9,
      name: "Giotto 32oz Leakproof BPA Free Drinking Water",
      slug: "giotto-32oz-leakproof-bpa-free-drinking-water-9",
      description:
        "With unique inspirational quote and time markers on it,this water bottle is great for measuring your daily intake of water,reminding you stay hydrated and drink enough water throughout the day.A must have for any fitness goals including weight loss,appetite control and overall health.",
      brand: "3M",
      category: "Home",
      price: 16.99,
      image: product19,
      hasFreeShipping: true,
      rating: 4,
    },
    date: "29 Dec 2020",
    buyer: {
      name: "Michael Cervantes",
      avatar: avatar8,
    },
    payment: {
      total: 960,
      received_payment_status: "Partially Paid",
      paid_amount: 866,
      status: "Confirmed",
    },
  },
  {
    product: {
      id: 13,
      name: "Laptop Bag",
      slug: "laptop-bag-13",
      description:
        "TSA FRIENDLY- A separate DIGI SMART compartment can hold 15.6 inch Laptop as well as 15 inch, 14 inch Macbook, 12.9 inch iPad, and tech accessories like charger for quick TSA checkpoint when traveling",
      brand: "TAS",
      category: "Bag",
      price: 29.99,
      image: product15,
      hasFreeShipping: true,
      rating: 5,
    },
    date: "15 Aug 2020",
    buyer: {
      name: "Nathaniel Marshall",
      avatar: avatar6,
    },
    payment: {
      total: 1423,
      received_payment_status: "Unpaid",
      paid_amount: 0,
      status: "Cancelled",
    },
  },
  {
    product: {
      id: 5,
      name: "Toshiba Canvio External Hard Drive",
      slug: "toshiba-canvio-advance-2-tb-portable-external-hard-drive-5",
      description: "Up to 3TB of storage capacity to store your growing files and content",
      brand: "Toshiba",
      category: "Storage Device",
      price: 69.99,
      image: product23,
      hasFreeShipping: true,
      rating: 2,
    },
    date: "03 Jan 2021",
    buyer: {
      name: "Tiffany Ross",
      avatar: avatar4,
    },
    payment: {
      total: 663,
      received_payment_status: "Partially Paid",
      paid_amount: 285,
      status: "Confirmed",
    },
  },
  {
    product: {
      id: 14,
      name: "Wireless Charger 5W Max",
      slug: "wireless-charger-5-w-max-14",
      description:
        "Charge with case: transmits charging power directly through protective cases. Rubber/plastic/TPU cases under 5 mm thickness . Do not use any magnetic and metal attachments or cards, or it will prevent charging.",
      brand: "3M",
      category: "Electronics",
      price: 10.83,
      image: product14,
      hasFreeShipping: true,
      rating: 3,
    },
    date: "20 Dec 2020",
    buyer: {
      name: "Philip Walters",
      avatar: null,
    },
    payment: {
      total: 1112,
      received_payment_status: "Partially Paid",
      paid_amount: 426,
      status: "Confirmed",
    },
  },
  {
    product: {
      id: 15,
      name: "Vankyo leisure 3 mini projector",
      slug: "3-m-filtrete-vacuum-belt-for-select-hoover-t-series-upright-vacuums-15",
      description:
        "SUPERIOR VIEWING EXPERIENCE: Supporting 1920x1080 resolution, VANKYO Leisure 3 projector is powered by MStar Advanced Color Engine, which is ideal for home entertainment. 2020 upgraded LED lighting provides a superior viewing experience for you.",
      brand: "Vankyo Store",
      category: "Projector",
      price: 99.99,
      image: product13,
      hasFreeShipping: true,
      rating: 2,
    },
    date: "02 Jul 2020",
    buyer: {
      name: "Pamela Smith",
      avatar: null,
    },
    payment: {
      total: 462,
      received_payment_status: "Partially Paid",
      paid_amount: 383,
      status: "Confirmed",
    },
  },
  {
    product: {
      id: 12,
      name: "Adidas Mens Tech Response Shoes",
      slug: "adidas-mens-tech-response-shoes-12",
      description:
        "Comfort + performance.  Designed with materials that are durable, lightweight and extremely comfortable. Core performance delivers the perfect mix of fit, style and all-around performance.",
      brand: "Adidas",
      category: "Shoes",
      price: 54.59,
      image: product16,
      hasFreeShipping: false,
      rating: 5,
    },
    date: "24 Jul 2020",
    buyer: {
      name: "Kara Gonzalez",
      avatar: avatar3,
    },
    payment: {
      total: 1325,
      received_payment_status: "Partially Paid",
      paid_amount: 792,
      status: "Confirmed",
    },
  },
  {
    product: {
      id: 18,
      name: "Logitech K380 Wireless Keyboard",
      slug: "acer-11-6-chromebook-intel-celeron-2-gb-memory-16-gb-e-mmc-flash-memory-moonstone-white-18",
      description:
        "Logitech K380 Bluetooth Wireless Keyboard gives you the comfort and convenience of desktop typing on your smartphone, and tablet. It is a wireless keyboard that connects to all Bluetooth wireless devices that support external keyboards. Take this compact, lightweight, Bluetooth keyboard anywhere in your home. Type wherever you like, on any compatible computer, phone or tablet.",
      brand: "Logitech",
      category: "Keyboard",
      price: 81.99,
      image: product10,
      hasFreeShipping: false,
      rating: 4,
    },
    date: "07 Jan 2021",
    buyer: {
      name: "Katherine Tate",
      avatar: avatar8,
    },
    payment: {
      total: 582,
      received_payment_status: "Partially Paid",
      paid_amount: 234,
      status: "Confirmed",
    },
  },
  {
    product: {
      id: 3,
      name: "Willful Smart Watch for Men Women 2020,",
      slug: "willful-smart-watch-for-men-women-2020-3",
      description:
        "Are you looking for a smart watch, which can not only easily keep tracking of your steps, calories, heart rate and sleep quality, but also keep you informed of incoming calls.",
      brand: "Willful",
      category: "Smart Watch",
      price: 29.99,
      image: product1,
      hasFreeShipping: true,
      rating: 5,
    },
    date: "29 Aug 2020",
    buyer: {
      name: "Ashley Douglas DDS",
      avatar: avatar3,
    },
    payment: {
      total: 1092,
      received_payment_status: "Fully Paid",
      paid_amount: 1092,
      status: "Completed",
    },
  },
  {
    product: {
      id: 22,
      name: "Switch Pro Controller",
      slug: "switch-pro-controller-22",
      brand: "Sharp",
      category: "Gaming",
      price: 429.99,
      image: product6,
      hasFreeShipping: false,
      rating: 3,
      description:
        "The Nintendo Switch Pro Controller is one of the priciest 'baseline' controllers in the current console\n generation, but it's also sturdy, feels good to play with, has an excellent direction pad, and features\n    impressive motion sensors and vibration systems. On top of all of that, it uses Bluetooth, so you don't need an\n    adapter to use it with your PC.",
    },
    date: "09 Jan 2021",
    buyer: {
      name: "Eric Gregory",
      avatar: avatar3,
    },
    payment: {
      total: 939,
      received_payment_status: "Fully Paid",
      paid_amount: 939,
      status: "Completed",
    },
  },
  {
    product: {
      id: 4,
      name: "Ronyes Unisex College Bag Bookbags for Women",
      slug: "ronyes-unisex-college-bag-bookbags-for-women-4",
      description:
        "Made of high quality water-resistant material; padded and adjustable shoulder straps; external USB with built-in charging cable offers a convenient charging",
      brand: "Ronyes",
      category: "Bag",
      price: 23.99,
      image: product24,
      hasFreeShipping: true,
      rating: 2,
    },
    date: "06 May 2020",
    buyer: {
      name: "Taylor Hernandez",
      avatar: avatar3,
    },
    payment: {
      total: 1129,
      received_payment_status: "Unpaid",
      paid_amount: 0,
      status: "Cancelled",
    },
  },
  {
    product: {
      id: 10,
      name: "Oculus Quest All-in-one VR",
      slug: "oculus-quest-all-in-one-vr-10",
      description:
        "All-in-one VR: No PC. No wires. No limits. Oculus quest is an all-in-one gaming system built for virtual reality. Now you can play almost anywhere with just a VR headset and controllers. Oculus touch controllers: arm yourself with the award-winning Oculus touch controllers. Your slashes, throws and grab appear in VR with intuitive, realistic Precision, transporting your hands and gestures right into the game",
      brand: "Oculus",
      category: "VR",
      price: 645,
      image: product18,
      hasFreeShipping: false,
      rating: 1,
    },
    date: "29 Dec 2020",
    buyer: {
      name: "Justin Patterson",
      avatar: avatar3,
    },
    payment: {
      total: 252,
      received_payment_status: "Fully Paid",
      paid_amount: 252,
      status: "Completed",
    },
  },
  {
    product: {
      id: 11,
      name: "Handbags for Women Large Designer bag",
      slug: "handbags-for-women-large-designer-bag-11",
      description:
        "Classic Hobo Purse: Top zipper closure, with 2 side zipper pockets design and elegant tassels decoration, fashionable and practical handbags for women, perfect for shopping, dating, travel and business",
      brand: "Hobo",
      category: "Bag",
      price: 39.99,
      image: product17,
      hasFreeShipping: true,
      rating: 3,
    },
    date: "19 Dec 2020",
    buyer: {
      name: "Judy Cummings",
      avatar: avatar3,
    },
    payment: {
      total: 1369,
      received_payment_status: "Fully Paid",
      paid_amount: 1369,
      status: "Completed",
    },
  },
  {
    product: {
      id: 18,
      name: "Logitech K380 Wireless Keyboard",
      slug: "acer-11-6-chromebook-intel-celeron-2-gb-memory-16-gb-e-mmc-flash-memory-moonstone-white-18",
      description:
        "Logitech K380 Bluetooth Wireless Keyboard gives you the comfort and convenience of desktop typing on your smartphone, and tablet. It is a wireless keyboard that connects to all Bluetooth wireless devices that support external keyboards. Take this compact, lightweight, Bluetooth keyboard anywhere in your home. Type wherever you like, on any compatible computer, phone or tablet.",
      brand: "Logitech",
      category: "Keyboard",
      price: 81.99,
      image: product10,
      hasFreeShipping: false,
      rating: 4,
    },
    date: "02 Jan 2021",
    buyer: {
      name: "Linda Buchanan",
      avatar: avatar7,
    },
    payment: {
      total: 351,
      received_payment_status: "Fully Paid",
      paid_amount: 351,
      status: "Completed",
    },
  },
  {
    product: {
      id: 21,
      name: "Google - Google Home",
      slug: "google-google-home-white-slate-fabric-21",
      brand: "Google",
      category: "Google Home",
      price: 129.29,
      image: product7,
      hasFreeShipping: true,
      rating: 4,
      description:
        "Simplify your everyday life with the Google Home, a voice-activated speaker powered by the Google Assistant. Use\n    voice commands to enjoy music, get answers from Google and manage everyday tasks. Google Home is compatible with\n    Android and iOS operating systems, and can control compatible smart devices such as Chromecast or Nest.",
    },
    date: "25 Feb 2021",
    buyer: {
      name: "Brian Perez",
      avatar: avatar8,
    },
    payment: {
      total: 506,
      received_payment_status: "Partially Paid",
      paid_amount: 497,
      status: "Confirmed",
    },
  },
  {
    product: {
      id: 3,
      name: "Willful Smart Watch for Men Women 2020,",
      slug: "willful-smart-watch-for-men-women-2020-3",
      description:
        "Are you looking for a smart watch, which can not only easily keep tracking of your steps, calories, heart rate and sleep quality, but also keep you informed of incoming calls.",
      brand: "Willful",
      category: "Smart Watch",
      price: 29.99,
      image: product1,
      hasFreeShipping: true,
      rating: 5,
    },
    date: "13 Sep 2020",
    buyer: {
      name: "Amy White",
      avatar: null,
    },
    payment: {
      total: 195,
      received_payment_status: "Fully Paid",
      paid_amount: 195,
      status: "Completed",
    },
  },
  {
    product: {
      id: 18,
      name: "Logitech K380 Wireless Keyboard",
      slug: "acer-11-6-chromebook-intel-celeron-2-gb-memory-16-gb-e-mmc-flash-memory-moonstone-white-18",
      description:
        "Logitech K380 Bluetooth Wireless Keyboard gives you the comfort and convenience of desktop typing on your smartphone, and tablet. It is a wireless keyboard that connects to all Bluetooth wireless devices that support external keyboards. Take this compact, lightweight, Bluetooth keyboard anywhere in your home. Type wherever you like, on any compatible computer, phone or tablet.",
      brand: "Logitech",
      category: "Keyboard",
      price: 81.99,
      image: product10,
      hasFreeShipping: false,
      rating: 4,
    },
    date: "30 Sep 2020",
    buyer: {
      name: "Katherine Clark",
      avatar: avatar1,
    },
    payment: {
      total: 1246,
      received_payment_status: "Partially Paid",
      paid_amount: 475,
      status: "Confirmed",
    },
  },
  {
    product: {
      id: 14,
      name: "Wireless Charger 5W Max",
      slug: "wireless-charger-5-w-max-14",
      description:
        "Charge with case: transmits charging power directly through protective cases. Rubber/plastic/TPU cases under 5 mm thickness . Do not use any magnetic and metal attachments or cards, or it will prevent charging.",
      brand: "3M",
      category: "Electronics",
      price: 10.83,
      image: product14,
      hasFreeShipping: true,
      rating: 3,
    },
    date: "26 Mar 2021",
    buyer: {
      name: "Jose Murphy",
      avatar: avatar5,
    },
    payment: {
      total: 383,
      received_payment_status: "Fully Paid",
      paid_amount: 383,
      status: "Completed",
    },
  },
  {
    product: {
      id: 2,
      name: "Bose Frames Tenor",
      slug: "bose-frames-tenor-rectangular-polarized-bluetooth-audio-sunglasses-2",
      description:
        "Redesigned for luxury \u2014 Thoughtfully refined and strikingly elegant, the latest Bose sunglasses blend enhanced features and designs for an elevated way to listen",
      brand: "Bose",
      category: "Glass",
      price: 249,
      image: product2,
      hasFreeShipping: false,
      rating: 4,
    },
    date: "01 Dec 2020",
    buyer: {
      name: "Jeffrey Rose",
      avatar: avatar5,
    },
    payment: {
      total: 902,
      received_payment_status: "Fully Paid",
      paid_amount: 902,
      status: "Completed",
    },
  },
  {
    product: {
      id: 24,
      name: "OneOdio A71 Wired Headphones",
      slug: "one-odio-a71-wired-headphones-24",
      brand: "OneOdio",
      category: "Headphone",
      price: 49.99,
      image: product4,
      hasFreeShipping: true,
      rating: 3,
      description:
        "Omnidirectional detachable boom mic upgrades the headphones into a professional headset for gaming, business,\n    podcasting and taking calls on the go. Better pick up your voice. Control most electric devices through voice\n    activation, or schedule a ride with Uber and order a pizza. OneOdio A71 Wired Headphones voice-controlled device\n    turns any home into a smart device on a smartphone or tablet.",
    },
    date: "15 Sep 2020",
    buyer: {
      name: "Amber Hunt",
      avatar: avatar7,
    },
    payment: {
      total: 379,
      received_payment_status: "Partially Paid",
      paid_amount: 174,
      status: "Confirmed",
    },
  },
  {
    product: {
      id: 2,
      name: "Bose Frames Tenor",
      slug: "bose-frames-tenor-rectangular-polarized-bluetooth-audio-sunglasses-2",
      description:
        "Redesigned for luxury \u2014 Thoughtfully refined and strikingly elegant, the latest Bose sunglasses blend enhanced features and designs for an elevated way to listen",
      brand: "Bose",
      category: "Glass",
      price: 249,
      image: product2,
      hasFreeShipping: false,
      rating: 4,
    },
    date: "08 Apr 2021",
    buyer: {
      name: "Christopher Haas",
      avatar: avatar2,
    },
    payment: {
      total: 7,
      received_payment_status: "Unpaid",
      paid_amount: 0,
      status: "Confirmed",
    },
  },
  {
    product: {
      id: 2,
      name: "Bose Frames Tenor",
      slug: "bose-frames-tenor-rectangular-polarized-bluetooth-audio-sunglasses-2",
      description:
        "Redesigned for luxury \u2014 Thoughtfully refined and strikingly elegant, the latest Bose sunglasses blend enhanced features and designs for an elevated way to listen",
      brand: "Bose",
      category: "Glass",
      price: 249,
      image: product2,
      hasFreeShipping: false,
      rating: 4,
    },
    date: "21 Oct 2020",
    buyer: {
      name: "Stephen Mccormick",
      avatar: avatar6,
    },
    payment: {
      total: 186,
      received_payment_status: "Partially Paid",
      paid_amount: 81,
      status: "Confirmed",
    },
  },
  {
    product: {
      id: 19,
      name: "OnePlus 7 Pro ",
      slug: "one-plus-7-pro-19",
      brand: "Philips",
      category: "Smart Phone",
      price: 14.99,
      image: product9,
      hasFreeShipping: false,
      rating: 4,
      description:
        "The OnePlus 7 Pro features a brand new design, with a glass back and front and curved sides. The phone feels\n    very premium but\u2019s it\u2019s also very heavy. The Nebula Blue variant looks slick but it\u2019s quite slippery, which\n    makes single-handed use a real challenge. It has a massive 6.67-inch \u2018Fluid AMOLED\u2019 display with a QHD+\n    resolution, 90Hz refresh rate and support for HDR 10+ content. The display produces vivid colours, deep blacks\n    and has good viewing angles.",
    },
    date: "21 Oct 2020",
    buyer: {
      name: "Matthew Reyes",
      avatar: avatar3,
    },
    payment: {
      total: 198,
      received_payment_status: "Fully Paid",
      paid_amount: 198,
      status: "Completed",
    },
  },
  {
    product: {
      id: 4,
      name: "Ronyes Unisex College Bag Bookbags for Women",
      slug: "ronyes-unisex-college-bag-bookbags-for-women-4",
      description:
        "Made of high quality water-resistant material; padded and adjustable shoulder straps; external USB with built-in charging cable offers a convenient charging",
      brand: "Ronyes",
      category: "Bag",
      price: 23.99,
      image: product24,
      hasFreeShipping: true,
      rating: 2,
    },
    date: "16 May 2020",
    buyer: {
      name: "Ricardo Morgan",
      avatar: avatar5,
    },
    payment: {
      total: 519,
      received_payment_status: "Partially Paid",
      paid_amount: 447,
      status: "Confirmed",
    },
  },
  {
    product: {
      id: 20,
      name: "Sony 4K Ultra HD LED TV ",
      slug: "sony-4-k-ultra-hd-led-tv-20",
      brand: "Apple",
      category: "Smart TV",
      price: 7999.99,
      image: product8,
      hasFreeShipping: false,
      rating: 5,
      description:
        "Sony 4K Ultra HD LED TV has 4K HDR Support. The TV provides clear visuals and provides distinct sound quality\n    and an immersive experience. This TV has Yes HDMI ports & Yes USB ports. Connectivity options included are HDMI.\n    You can connect various gadgets such as your laptop using the HDMI port. The TV comes with a 1 Year warranty.",
    },
    date: "01 Jul 2020",
    buyer: {
      name: "William Castillo",
      avatar: avatar4,
    },
    payment: {
      total: 10,
      received_payment_status: "Partially Paid",
      paid_amount: 6,
      status: "Confirmed",
    },
  },
  {
    product: {
      id: 11,
      name: "Handbags for Women Large Designer bag",
      slug: "handbags-for-women-large-designer-bag-11",
      description:
        "Classic Hobo Purse: Top zipper closure, with 2 side zipper pockets design and elegant tassels decoration, fashionable and practical handbags for women, perfect for shopping, dating, travel and business",
      brand: "Hobo",
      category: "Bag",
      price: 39.99,
      image: product17,
      hasFreeShipping: true,
      rating: 3,
    },
    date: "04 Jul 2020",
    buyer: {
      name: "James Coleman",
      avatar: avatar8,
    },
    payment: {
      total: 897,
      received_payment_status: "Partially Paid",
      paid_amount: 677,
      status: "Confirmed",
    },
  },
  {
    product: {
      id: 18,
      name: "Logitech K380 Wireless Keyboard",
      slug: "acer-11-6-chromebook-intel-celeron-2-gb-memory-16-gb-e-mmc-flash-memory-moonstone-white-18",
      description:
        "Logitech K380 Bluetooth Wireless Keyboard gives you the comfort and convenience of desktop typing on your smartphone, and tablet. It is a wireless keyboard that connects to all Bluetooth wireless devices that support external keyboards. Take this compact, lightweight, Bluetooth keyboard anywhere in your home. Type wherever you like, on any compatible computer, phone or tablet.",
      brand: "Logitech",
      category: "Keyboard",
      price: 81.99,
      image: product10,
      hasFreeShipping: false,
      rating: 4,
    },
    date: "19 Feb 2021",
    buyer: {
      name: "Michael Summers",
      avatar: avatar3,
    },
    payment: {
      total: 653,
      received_payment_status: "Fully Paid",
      paid_amount: 653,
      status: "Completed",
    },
  },
  {
    product: {
      id: 3,
      name: "Willful Smart Watch for Men Women 2020,",
      slug: "willful-smart-watch-for-men-women-2020-3",
      description:
        "Are you looking for a smart watch, which can not only easily keep tracking of your steps, calories, heart rate and sleep quality, but also keep you informed of incoming calls.",
      brand: "Willful",
      category: "Smart Watch",
      price: 29.99,
      image: product1,
      hasFreeShipping: true,
      rating: 5,
    },
    date: "03 Mar 2021",
    buyer: {
      name: "Jeremiah Espinoza",
      avatar: avatar2,
    },
    payment: {
      total: 913,
      received_payment_status: "Partially Paid",
      paid_amount: 468,
      status: "Confirmed",
    },
  },
  {
    product: {
      id: 2,
      name: "Bose Frames Tenor",
      slug: "bose-frames-tenor-rectangular-polarized-bluetooth-audio-sunglasses-2",
      description:
        "Redesigned for luxury \u2014 Thoughtfully refined and strikingly elegant, the latest Bose sunglasses blend enhanced features and designs for an elevated way to listen",
      brand: "Bose",
      category: "Glass",
      price: 249,
      image: product2,
      hasFreeShipping: false,
      rating: 4,
    },
    date: "03 Mar 2021",
    buyer: {
      name: "Tyler Brooks",
      avatar: null,
    },
    payment: {
      total: 1123,
      received_payment_status: "Fully Paid",
      paid_amount: 1123,
      status: "Completed",
    },
  },
  {
    product: {
      id: 17,
      name: "Nike Air Max",
      slug: "72-9301-speaker-wire-harness-adapter-for-most-plymouth-dodge-and-mitsubishi-vehicles-multi-17",
      description:
        "With a bold application of colorblocking inspired by modern art styles, the Nike Air Max 270 React sneaker is constructed with layers of lightweight material to achieve its artful look and comfortable feel.",
      brand: "Nike",
      category: "Shoes",
      price: 81.99,
      image: product11,
      hasFreeShipping: true,
      rating: 5,
    },
    date: "29 Dec 2020",
    buyer: {
      name: "Juan Wilson",
      avatar: avatar3,
    },
    payment: {
      total: 779,
      received_payment_status: "Fully Paid",
      paid_amount: 779,
      status: "Completed",
    },
  },
  {
    product: {
      id: 15,
      name: "Vankyo leisure 3 mini projector",
      slug: "3-m-filtrete-vacuum-belt-for-select-hoover-t-series-upright-vacuums-15",
      description:
        "SUPERIOR VIEWING EXPERIENCE: Supporting 1920x1080 resolution, VANKYO Leisure 3 projector is powered by MStar Advanced Color Engine, which is ideal for home entertainment. 2020 upgraded LED lighting provides a superior viewing experience for you.",
      brand: "Vankyo Store",
      category: "Projector",
      price: 99.99,
      image: product13,
      hasFreeShipping: true,
      rating: 2,
    },
    date: "03 Dec 2020",
    buyer: {
      name: "Marvin Duran",
      avatar: null,
    },
    payment: {
      total: 594,
      received_payment_status: "Unpaid",
      paid_amount: 0,
      status: "Cancelled",
    },
  },
  {
    product: {
      id: 22,
      name: "Switch Pro Controller",
      slug: "switch-pro-controller-22",
      brand: "Sharp",
      category: "Gaming",
      price: 429.99,
      image: product6,
      hasFreeShipping: false,
      rating: 3,
      description:
        "The Nintendo Switch Pro Controller is one of the priciest 'baseline' controllers in the current console\n    generation, but it's also sturdy, feels good to play with, has an excellent direction pad, and features\n impressive motion sensors and vibration systems. On top of all of that, it uses Bluetooth, so you don't need an\n    adapter to use it with your PC.",
    },
    date: "28 May 2020",
    buyer: {
      name: "Jessica Glass",
      avatar: avatar5,
    },
    payment: {
      total: 1065,
      received_payment_status: "Partially Paid",
      paid_amount: 844,
      status: "Confirmed",
    },
  },
  {
    product: {
      id: 18,
      name: "Logitech K380 Wireless Keyboard",
      slug: "acer-11-6-chromebook-intel-celeron-2-gb-memory-16-gb-e-mmc-flash-memory-moonstone-white-18",
      description:
        "Logitech K380 Bluetooth Wireless Keyboard gives you the comfort and convenience of desktop typing on your smartphone, and tablet. It is a wireless keyboard that connects to all Bluetooth wireless devices that support external keyboards. Take this compact, lightweight, Bluetooth keyboard anywhere in your home. Type wherever you like, on any compatible computer, phone or tablet.",
      brand: "Logitech",
      category: "Keyboard",
      price: 81.99,
      image: product10,
      hasFreeShipping: false,
      rating: 4,
    },
    date: "17 May 2020",
    buyer: {
      name: "Gary Herman",
      avatar: avatar8,
    },
    payment: {
      total: 432,
      received_payment_status: "Partially Paid",
      paid_amount: 64,
      status: "Confirmed",
    },
  },
  {
    product: {
      id: 19,
      name: "OnePlus 7 Pro ",
      slug: "one-plus-7-pro-19",
      brand: "Philips",
      category: "Smart Phone",
      price: 14.99,
      image: product9,
      hasFreeShipping: false,
      rating: 4,
      description:
        "The OnePlus 7 Pro features a brand new design, with a glass back and front and curved sides. The phone feels\n    very premium but\u2019s it\u2019s also very heavy. The Nebula Blue variant looks slick but it\u2019s quite slippery, which\n    makes single-handed use a real challenge. It has a massive 6.67-inch \u2018Fluid AMOLED\u2019 display with a QHD+\n    resolution, 90Hz refresh rate and support for HDR 10+ content. The display produces vivid colours, deep blacks\n    and has good viewing angles.",
    },
    date: "25 Mar 2021",
    buyer: {
      name: "Adam Williams",
      avatar: avatar2,
    },
    payment: {
      total: 1402,
      received_payment_status: "Partially Paid",
      paid_amount: 434,
      status: "Confirmed",
    },
  },
  {
    product: {
      id: 20,
      name: "Sony 4K Ultra HD LED TV ",
      slug: "sony-4-k-ultra-hd-led-tv-20",
      brand: "Apple",
      category: "Smart TV",
      price: 7999.99,
      image: product8,
      hasFreeShipping: false,
      rating: 5,
      description:
        "Sony 4K Ultra HD LED TV has 4K HDR Support. The TV provides clear visuals and provides distinct sound quality\n    and an immersive experience. This TV has Yes HDMI ports & Yes USB ports. Connectivity options included are HDMI.\n    You can connect various gadgets such as your laptop using the HDMI port. The TV comes with a 1 Year warranty.",
    },
    date: "13 Apr 2021",
    buyer: {
      name: "Bobby Brown",
      avatar: null,
    },
    payment: {
      total: 100,
      received_payment_status: "Partially Paid",
      paid_amount: 65,
      status: "Confirmed",
    },
  },
  {
    product: {
      id: 14,
      name: "Wireless Charger 5W Max",
      slug: "wireless-charger-5-w-max-14",
      description:
        "Charge with case: transmits charging power directly through protective cases. Rubber/plastic/TPU cases under 5 mm thickness . Do not use any magnetic and metal attachments or cards, or it will prevent charging.",
      brand: "3M",
      category: "Electronics",
      price: 10.83,
      image: product14,
      hasFreeShipping: true,
      rating: 3,
    },
    date: "07 Aug 2020",
    buyer: {
      name: "Sharon Moss",
      avatar: avatar8,
    },
    payment: {
      total: 823,
      received_payment_status: "Unpaid",
      paid_amount: 0,
      status: "Cancelled",
    },
  },
  {
    product: {
      id: 15,
      name: "Vankyo leisure 3 mini projector",
      slug: "3-m-filtrete-vacuum-belt-for-select-hoover-t-series-upright-vacuums-15",
      description:
        "SUPERIOR VIEWING EXPERIENCE: Supporting 1920x1080 resolution, VANKYO Leisure 3 projector is powered by MStar Advanced Color Engine, which is ideal for home entertainment. 2020 upgraded LED lighting provides a superior viewing experience for you.",
      brand: "Vankyo Store",
      category: "Projector",
      price: 99.99,
      image: product13,
      hasFreeShipping: true,
      rating: 2,
    },
    date: "23 Feb 2021",
    buyer: {
      name: "Scott Buchanan",
      avatar: avatar5,
    },
    payment: {
      total: 183,
      received_payment_status: "Unpaid",
      paid_amount: 0,
      status: "Cancelled",
    },
  },
]);
